
Header header


float64 ICPV_Cmd_StrAngle    # 方向盘转角控制指令
float64 ICPV_Cmd_StrAngleLimit    # 方向盘转角限制指令
float64 ICPV_Cmd_EPSXBW_En    # 方向盘使能
float64 ICPV_Cmd_EPSDir    # 方向盘转向灯控制指令
float64 ICPV_Cmd_StrAngleSpd    # 方向盘转角变化率指令
float64 ICPV_Cmd_AccPelPosAct    # 加速踏板开度指令
float64 ICPV_Cmd_AccPelPosActInv    # 冗余加速踏板开度指令
float64 ICPV_Cmd_BrkPelPosAct    # 制动踏板开度指令
float64 ICPV_Cmd_BrkPelPosActInv    # 冗余制动踏板开度指令
float64 ICPV_Cmd_BrkPelEnable    # 制动踏板使能
float64 ICPV_Cmd_AccPelEnable    # 加速踏板使能
float64 ICPV_Cmd_BrakeLightReq    # 制动灯控制指令
float64 ICPV_Cmd_TgtSft    # 档位控制指令
float64 ICPV_Cmd_TgtSftEnable    # 档位控制使能
float64 ICPV_Cmd_ATOModEnable    # 自动驾驶模式使能


float64 VCU1_ICPV_EPSDir    # 实际的方向盘状态
float64 VCU1_ICPV_StrAngle    # 实际方向盘转角
float64 VCU1_ICPV_StrAngleSpd    # 实际方向盘转角速率
float64 VCU1_ICPV_StrAngleFb    # 接收到方向盘转角
float64 VCU1_ICPV_EPSMODE    # 方向盘状态反馈
float64 VCU1_ICPV_StrAngleSpdDir    # 接收到转向灯指令
float64 VCU1_ICPV_YawRate    # 横摆角速度
float64 VCU1_ICPV_LongAcc    # 纵向加速度
float64 PCU_ICPV_TMDirSts    # 车辆前进的方向
float64 VCU1_ICPV_ESCWhlRRSpd    # 右后轮轮速
float64 VCU1_ICPV_ESCWhlRLSpd    # 左后轮轮速
float64 VCU1_ICPV_ESCWhlFRSpd    # 右前轮轮速
float64 VCU1_ICPV_ESCWhlFLSpd    # 左前轮轮速
float64 VCU1_ICPV_VehSpd    # 车速
float64 VCU_IPCV_BrkLgtSts    # 制动灯状态反馈
float64 VUC_ICPV_AccPed    # 实际加速踏板开度
float64 VUC_ICPV_BrkPed    # 实际制动踏板开度
float64 VCU_ICPV_AccPelPosFb    # 接收到的加速踏板开度指令
float64 VCU_ICPV_BrkPelPosFb    # 接收到的加速踏板开度指令
float64 VCU_ICPV_TgtSftFb    # 接收到的档位指令
float64 VCU_ICPV_AccPelSta    # 加速踏板状态
float64 VCU_ICPV_BrkPelSta    # 制动踏板状态
float64 VCU_ICPV_ATOModFb    # 自动驾驶模式反馈
float64 VCU_ICPV_VCUSta
float64 VCU_ICPV_CruiseControlSts
float64 VCU_ICPV_CruiseSwitchSts
float64 VCU_ICPV_EPBSysVCU
float64 VCU_ICPV_VCUGearLevPos
float64 VCU1_ICPV_BackDoorSts

float64 target_yaw
float64 target_vel
float64 target_x
float64 target_y
float64 target_time

